---
- name: set-up DNS and Dependencies
  hosts: all
  become: yes
  tasks:


    - name: add 8.8.8.8
      ansible.builtin.lineinfile:
       path: /etc/resolv.conf
       line: nameserver 8.8.8.8
       create: yes



#    - name: add 8.8.8.8
#       lineinfile:
#       path: "/etc/resolv.conf"
#       line: nameserver 8.8.8.8
#
    - name: update_cache
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true
