---
- name: set-up DNS ubuntu 22 or less
  hosts: all
  become: yes
  tasks:

    - name: A침adir DNS 8.8.8.8 solo si no est치 presente
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 8.8.8.8'

    - name: A침adir DNS 8.8.4.4 solo si no est치 presente
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 8.8.4.4'

    - name: update_cache
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true

    - name: install resolvconf
      ansible.builtin.package:
        name: resolvconf
        state: present

    - name: enable resolvconf
      shell: |
        systemctl enable resolvconf.service
        systemctl start resolvconf.service

    - name: modify resolv.conf package
      lineinfile:
        path: /etc/resolvconf/resolv.conf.d/head
        line: nameserver 8.8.8.8

    - name: modify resolv.conf package
      lineinfile:
        path: /etc/resolvconf/resolv.conf.d/head
        line: nameserver 8.8.4.4

    - name: update resolvconf package
      become: yes
      shell: |
        resolvconf --enable-updates
        resolvconf -u

