---
- name: Instalar Docker 27.5.1
  hosts: all
  become: true
  gather_facts: true

  vars:

    # Versiones solicitadas
    docker_version: "27.5.1"
    docker_epoch: "5"
    user: mw
    prereq_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common

  pre_tasks:
    - name: Comprobar familia de SO soportada
      assert:
        that: ansible_os_family == "Debian"
        fail_msg: "Este playbook está preparado para Debian/Ubuntu."

    - name: Asegurar carpeta de keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

  tasks:
    # ---------- Repositorio Docker ----------
    - name: Instalar prerequisitos
      apt:
        name: "{{ prereq_packages }}"
        state: present
        update_cache: yes

    - name: Descargar clave GPG de Docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Convertir clave GPG de Docker a keyring
      command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Añadir repo oficial de Docker (Ubuntu)
      apt_repository:
        filename: docker
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        update_cache: yes

    - name: Instalar Docker 27.5.1 (pin explícito)
      apt:
        name:
          - "docker-ce={{ docker_epoch }}:{{ docker_version }}*"
          - "docker-ce-cli={{ docker_epoch }}:{{ docker_version }}*"
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
        force_apt_get: yes
        dpkg_options: "force-confdef,force-confold"

    - name: Configurar Docker daemon.json (cgroupdriver=systemd)
      copy:
        dest: /etc/docker/daemon.json
        mode: "0644"
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": { "max-size": "10m" },
            "storage-driver": "overlay2"
          }
      notify: Restart Docker

    - name: Habilitar y arrancar Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: adding existing user '{{ user }}' to group sudo
      user:
        name: '{{ user }}'
        groups: sudo,docker
        append: yes
