---
- name: set dns
  hosts: all
  become: yes
  tasks:

    - name: A침adir DNS 8.8.8.8 solo si no est치 presente
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 8.8.8.8'

    - name: A침adir DNS 8.8.4.4 solo si no est치 presente
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 8.8.4.4'
